title: Aishwarya Linesh Thakur's homepage
description: Bookmark this to keep an eye on my project updates!
theme: null
plugins:
  - jekyll-remote-theme

# Navigation bar pages
header_pages:
  - index.md
  - 09-skills-profiles.md
  - 02-education.md
