title: Aishwarya Linesh Thakur's homepage
description: Bookmark this to keep an eye on my project updates!
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Navigation bar pages
header_pages:
  - index.md
  - 09-skills-profiles.md
  - 02-education.md
