title: Aishwarya Linesh Thakur's homepage
description: Bookmark this to keep an eye on my project updates!
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- remote_theme: pages-themes/leap-day@v0.2.0
